targets:
  $default:
    builders:
      flutter_assets_integrity_checker|masterAssetHashBuilder:
        generate_for:
          - asset_integrity.yaml

builders:
  masterAssetHashBuilder:
    import: "package:flutter_assets_integrity_checker/src/tool/builder.dart"
    builder_factories: ["masterAssetHashBuilder"]
    build_extensions: { "$package$": ["lib/generated/master_asset_hash.dart"] }
    auto_apply: root_package
    build_to: source
