name: flutter_assets_integrity_checker
description: A Flutter package to verify asset integrity using a master hash.
version: 1.0.3
homepage: https://github.com/rvdrover/flutter_assets_integrity_checker
repository: https://github.com/rvdrover/flutter_assets_integrity_checker
issue_tracker: https://github.com/rvdrover/flutter_assets_integrity_checker/issues

publish_to: none
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  crypto: ^3.0.6
  yaml: ^3.1.3
  build: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

